### ISSUE TITLE
It is impossible to lose

### ISSUE THREAD

**Issue by craftyguy** [SecUSo/privacy-friendly-dame#9] opened 2019-03-04 21:16 UTC
There seems to be no way that the player can lose the game when playing against the bot. Even if all the white pieces are gone, the 'congratulations you have defeated your opponent' box still pops up.

**Comment by g-whiz** [comment] 2019-04-17 05:08
Additionally, while not a bug, the bot's strategy (random choice of valid moves) makes the single player version quite boring.

Would you be interested in an implementation of a strategy that is a bit more... challenging?

**Comment by Kamuno** [comment] 2019-08-16 05:26
Fixed with commit 8025e4537559c33c54024c2ba3980eb714767582

**Closed by Kamuno** 2019-08-16 05:26 UTC
Labels: bug
