### ISSUE TITLE
Eat more than two pieces

### ISSUE THREAD

**Issue by maverick74** [SecUSo/privacy-friendly-dame#18] opened 2020-06-09 12:57 UTC
It would be good to be able to "eat" more than two pieces if we have them available

**Comment by Kamuno** [comment] 2020-06-09 20:31
What exactly do you mean by that? Could you elaborate?

**Comment by maverick74** [comment] 2020-06-12 10:49
imagine i have a king and that, with that king, i can capture (that's what i meant with "eat") three other pieces...

I got into this situation and was only able to capture 2 at once.

If i'm not clear enough, please say so and i'll try to elaborate some more (english is not my native language, so...)

**Comment by sleep-yearning** [comment] 2020-06-12 12:01
Hey @maverick74 , we couldn't reproduce the issue you described. 
If it is possible for you, please add a screenshot of such a situation. 
In general, pieces should only be captured, if the field directly behind them is free, but continously as long as pieces are divided by 1 empty field. 
Just to make sure there is no misunderstanding. :)

**Comment by maverick74** [comment] 2020-06-14 16:23
That's funny!!!

That happened the first time I played, but now I've tried to replicate it a few times and I'm not able too either...

Maybe I didn't seen it well enough.............

**Comment by sleep-yearning** [comment] 2020-06-16 12:30
Alright, then I'm gonna close this for now. 
If it happens again, feel free to reopen.

**Closed by sleep-yearning** 2020-06-16 12:30 UTC
Labels: enhancement
